#! /bin/sh
#rm -rf docs
rm src/xtend+yepnope.js
cat src/yepnope.js src/xtend.js >> src/xtend+yepnope.js
uglifyjs -o bin/xtend.min.js -nc src/xtend.js
uglifyjs -o bin/xtend+yepnope.min.js -nc src/xtend+yepnope.js
lib/node-jsdoc-toolkit/app/run.js -c=lib/xtend.jsdoc.conf
